version: 2



build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

# Установка среды выполнения
python:
  install:
    - requirements: docs/requirements.txt

# Настройки сборки документации
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
  fail_on_error: true
  output:
    directory: docs/_build/html
  requirements_file: docs/requirements.txt
  parallel_build:
    - -j4

# Стадии сборки
formats: all