version: 2



build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

# Установка среды выполнения
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

# Настройки сборки документации
sphinx:
  configuration: test_doc/source/conf.py
  

# Стадии сборки