version: 2

# Установка среды выполнения
python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt

# Настройки сборки документации
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
  fail_on_error: true
  output:
    directory: docs/_build/html
  requirements_file: docs/requirements.txt
  parallel_build:
    - -j4

# Стадии сборки
formats: all